/*도서 INSERT*/


INSERT INTO BOOK VALUES(BOOK_CODE_PK.NEXTVAL, '미드나잇 라이브러리', '매트 헤이그', '인플루엔셜', '영미소설', 14000);

INSERT INTO MEMBER VALUES(MEMBER_CODE_PK.NEXTVAL, 'MINGU', 'MINJU123', '정민구', 23, '010-9999-9999', NULL, 0);

INSERT INTO RENTAL VALUES(RETAL_CODE_PK.NEXTVAL, DEFAULT, DEFAULT, MEMBER_CODE_PK.CURRVAL, BOOK_CODE_PK.CURRVAL);

DROP SEQUENCE MEMBER_CODE_PK;
DROP SEQUENCE RETAL_CODE_PK;
DROP SEQUENCE REVIEW_CODE_PK;
DROP SEQUENCE BOOK_CODE_PK;


CREATE SEQUENCE MEMBER_CODE_PK
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE RETAL_CODE_PK
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE REVIEW_CODE_PK
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BOOK_CODE_PK
START WITH 1
INCREMENT BY 1;


DELETE FROM BOOK;
DELETE FROM MEMBER;
DELETE FROM RENTAL;