DELETE FROM REVIEW;
DELETE FROM RENTAL;
DELETE FROM BOOK;
DELETE FROM MEMBER;

ALTER TABLE MEMBER DROP COLUMN POINT;

DROP SEQUENCE MEMBER_CODE_PK;
DROP SEQUENCE RENTAL_CODE_PK;
DROP SEQUENCE REVIEW_CODE_PK;
DROP SEQUENCE BOOK_CODE_PK;

CREATE SEQUENCE MEMBER_CODE_PK
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE RENTAL_CODE_PK
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE REVIEW_CODE_PK
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BOOK_CODE_PK
START WITH 1
INCREMENT BY 1;